### PR TITLE
Get HL2SB compiling

### PR DESCRIPTION
**Pull request by luttje**
Pardon the messy commit. I turned off code formatting too late and checking every file line-by-line to fix it is too time consuming (plus I've been at that for some time, getting this to compile).

This PR is the result of my own project being merged over top HL2SB. My own project is the result of a fresh clone from [SourceSDK 2013 by Valve] (https://github.com/ValveSoftware/source-sdk-2013) with HL2SB code slowly copied over to it.

It is pretty late, so I'm just info dumping a bit now, some notes/todo's:
- [ ] I commented the mounting of games and addons, because I wasn't using it in my project. Its still disabled here
- [ ] Same goes for the ARGG, I have yet to enable it:
  broken ARGG
- [ ] On launching the game you'll get two asserts which you can pass by clicking "Ignore Asserts in This File" (the second assert repeats a hundred times and ends up spamming your console)
  assert one
  assert that spams
- [ ] It seems I commented the player model selectionin hl2mp_gamerules.cpp under ClientSettingsChanged because my project didnt require it
- [ ] Same for episodic content like IsAlyxInDarknessMode
- [ ] I included the HL2SB game project here, because its required to test and play. Having it in a seperate repo seems cumbersome to me, besides I:
  - [x] made some changes to the `cfg/settings*.src` files to enable the gamemode picker. 
  - [x] I fixed the `gameinfo.txt` using deprecated keyvalues
  - [x] Fixed the Lua code which didn't provide the required first argument to `surface.AddCustomFontFile`
  - [ ] Do let me know if you all want to keep it separated. But I think a monorepo might be more useful to keep every souce file in sync. We could create a GitHub action to compile and zip a release here as well, to make it easier to download for non-technical users.
- [ ] To prevent future formatting trouble, I propose including a `.clang-format`. We can direct our IDE's to respect that in the future. I've included an example.
- [x] [These changes by tonysergi](https://github.com/tonysergi/source-sdk-2013) are included, since I copied those over in my project, on which this merge is based.
- [x] I called the missing `PlayerUpdateFlashlight`
- [x] Added a getting started, to help contributors going
- [x] Added a little bash script (`src/setupprojects.sh`) to quickly setup debugging (because the vpc scripts mess that up when they touch the vs project files)
- [ ] There's an occasional heap error in CClassMap::Add and RemoveAllScripted caused by removing items whilst iterating forward. Should reverse the loop instead, e.g:
```cpp
void CClassMap::RemoveAllScripted(void) {
    int c = m_ClassDict.Count();
    int i;

    for ( i = c - 1; i >= 0; i-- )
    {
        classentry_t *lookup = &m_ClassDict[i];
        if ( !lookup )
            continue;

        if ( lookup->scripted )
        {
            m_ClassDict.RemoveAt( i );
        }
    }
}
```

I've done my best to remove any changes I made that are irrelevant to this project. However I've likely missed some.

I'm making this a draft merge. I'd like some guidance on how to best clean this PR up, so the merge becomes reviewable.

## Additional notes
I'll use this list to track additional issues I find in my own project, that need fixing in HL2SB as well. They're not all related to this PR, so feel free to ask me to make separate PR's/issues for each of them.

- [ ] Implement this fix for animations: https://developer.valvesoftware.com/wiki/SDK_Known_Issues_List_Fixed#Thirdperson_player_animations_look_like_.22Ice_Skating.22
- [ ] Change `const char *zipPath = NULL;` to `const char *zipPath = relativePath;` in luacachefile.cpp to fix constructing cache files
- [ ] <s>Ensure the lua_cache path is added as a search path, so downloaded gamemodes actually load if the client doesn't already have it in their gamemodes folder. I did this by adding this to the end of `luasrc_ExtractLcf` (and refactoring it slightly so the `gamePath` var is available in the same scope):</s> This can also be done by properly implementing mountaddons.cpp (which I had removed in my mod)
```cpp
#ifdef CLIENT_DLL
    // Add the cache folder to the Lua path, so clients can load files from it.
    char cacheDirectoryPath[MAX_PATH];
    Q_strncpy( cacheDirectoryPath, gamePath, sizeof( cacheDirectoryPath ) );
    Q_strncat( cacheDirectoryPath, "\\" LUA_PATH_CACHE, sizeof( cacheDirectoryPath ), COPY_ALL_CHARACTERS );
    filesystem->AddSearchPath( cacheDirectoryPath, "MOD" );
#endif
```
- [ ] In luamanager.cpp the content path is incorrectly added relatively (should be absolute). Replace `filesystem->AddSearchPath( contentSearchPath, "MOD" );` with something like:
```cpp
#ifdef CLIENT_DLL
    const char *gamePath = engine->GetGameDirectory();
#else
    char gamePath[256];
    engine->GetGameDir( gamePath, 256 );
#endif
    Q_strncpy( contentSearchPath, gamePath, sizeof( contentSearchPath ) );
    Q_strncat( contentSearchPath, "\\gamemodes\\", sizeof( contentSearchPath ) );
    Q_strncat( contentSearchPath, gamemode, sizeof( contentSearchPath ) );
    Q_strncat( contentSearchPath, "\\content", sizeof( contentSearchPath ) );

    filesystem->AddSearchPath( contentSearchPath, "GAME" ); // I made this GAME, so the source engine is able to download content to clients
```

### CODE REVIEW

**Comment by andrewmcwatters** [comment]
I agree it's time to reunify these repositories. We did it back in the Google Code days for a specific reason that no longer applies. We should push binaries to [Releases](https://github.com/Planimeter/hl2sb-src/releases) so we don't end up inflating the repository in the same way we bloated the trunk history way back.

I agree with your approach of using [ValveSoftware/source-sdk-2013](https://github.com/ValveSoftware/source-sdk-2013) and then reintroducing hl2sb. I think I'm forced to not attach this repository to the fork network there simply because Half-Life 2: Sandbox existed before their repository was released, so we literally predate them since the mod was first built on the 2006 branch.

I think your approach across the board and what you chose to include is great.

I'll try to do the hardwork of replicating this patch while preserving individual diffs. I'd like us to be able to see specific commits that address individual concerns. So for example, we could `git cherry-pick` Tony's work to be imported and preserve the commits.

Edit: While we're at it, do we want to move to Visual Studio 2022?

Maybe the process for replicating this patch is something like:

- [x] Fork [ValveSoftware/source-sdk-2013](https://github.com/ValveSoftware/source-sdk-2013)
- [x] Port to Visual Studio 2022
- [ ] `git cherry-pick` from tonysergi/source-sdk-2013
- [x] cp hl2sb-src/* source-sdk-2013
- [x] Verify build
- [x] Manually verify diffs
- [ ] Reintroduce history into `master`
- [ ] `git tag`
- [ ] Create a new release

Roughly speaking, of course. Building from upstream should take place first. Of course if we could also automate this from GitHub Actions, that would be ideal. I've failed to do it in the past, though, but at the time I was using vs2013. Maybe I could get it to work with vs2022.

**Comment by luttje** [comment]
Do you think its worth the hassle of keeping in sync with valve's repo? I imagine with source 2 now, that the older engines may get neglected.

Also another option for a cleaner merge might be to apply a code styling to all files in the master branch of hl2sb-src, committing that. Afterwards doing the same to these changes, then commit a PR. It should reduce the changes to only code and no formatting

**Comment by andrewmcwatters** [comment]
Yeah, I doubt we'll ever see another push to source-sdk-2013, so it's probably not important. Even if we hypothetically needed to synchronize across disparate histories, git sort of lets you do it, it just tells you that you shouldn't.

**Comment by luttje** [comment]
I went ahead and did it (since it seemed easy enough): https://github.com/luttje/hl2sb-src/commit/137d5ef03facb189dff0decf6aee5530e654fee4

This diff is a lot cleaner and should be easier to work with.

Given the whole XZ utils incident I think it might be a good exercise for us if you pick a clang-format styling and apply that to the repo. Then I'll propose a new PR into that so the changes can be cleanly inspected.

For reference, here's my process:

1. Created a new branch `fix/clean-merge`

1. Copy over HL2SB game files, commit

2. Add .clang-format with style rules

3. Run command: `find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|c\|h\)' -exec clang-format -style=file -i {} \;`

4. Commit

5. Switch to `fix/get-it-to-compile`

6. Applied the same .clang-format and command to this branch

5. Copy all files over to `fix/clean-merge` (replacing all), commit

For better formatting in the future we should use `// clang-format off` / and `// clang-format on` around macro sections (e.g: see compiledcaptionswap.cpp), since it doesn't seem possible to get those to style nicely.

**Comment by andrewmcwatters** [comment]
I'm in communication with a Russian community about bringing on another developer, so I haven't lost sight of this. I'm just juggling at the moment.

**Comment by luttje** [comment]
Alright! 

I'm pretty far with my own project (which I'll eventually open-source). It's turning out very similar to HL2SB and Garry's Mod, except I'm heading more in the same direction as Garry's Mod: naming Lua bindings differently from source engine functions, customizing Lua, etc. So I feel like both can exist fine side-by-side.

Once it's a bit easier to make PR's here I will make some, of course in the style of the HL2SB project where they mimic the source engine naming/functionality as closely as possible.

**Comment by andrewmcwatters** [comment]
###### Internal note

Created tag `2007` to pin Source Engine 2007 latest build. Pending `source-sdk-2013` rebuild.

**Comment by andrewmcwatters** [comment]
###### Internal notes

##### TODO

- [x] Create `Source Engine 2007` .patch against `MyMod`
- [x] Port `Source Engine 2007` .patch to `ValveSoftware/source-sdk-2013`
- [ ] Create empty branch commit (`git switch --orphan 2013`)
- [ ] **(Additional)** Import `tonysergi/source-sdk-2013`

**Comment by andrewmcwatters** [comment]
See also: #16

**Comment by luttje** [comment]
Good to see you've got the 2007 version tagged!

Just popping in to note that I've made my own project public: https://github.com/experiment-games/experiment-source It may contain some useful code to anyone reading this (now or in the future).

Once hl2sb is cleaned up and ready for contributions I'll port some features over.

**Comment by andrewmcwatters** [comment]
###### Internal note

image

Start backport of `hl2sb-src` to `MyMod-2007`, schedule .patch release for Monday.

Edit: Reschedule for 11/25.

**Comment by andrewmcwatters** [comment]
OK, this now promoted to [Planimeter/hl2sb-2013 `feature/port`](https://github.com/Planimeter/hl2sb-2013/tree/feature/port). The port effort is large enough that I'm addressing it in parts in this feature branch, and we're now on the fork network for [ValveSoftware/source-sdk-2013](https://github.com/ValveSoftware/source-sdk-2013).

**Comment by andrewmcwatters** [comment]
`Planimeter/source-sdk-2013-VS2022` has been released, and `Planimeter/hl2sb-2013` has a merged remote-tracking branch against it.

We're moving forward with updating VPC scripts before Christmas.

**Comment by andrewmcwatters** [comment]
There are some portability concerns that @itzvladik had spotted and he's resolved. We've mostly merged this work forward tonight. This may bleed into Monday.

Seeing some odd compilation issues we didn't see prior to forward-merging hl2sb-2007. Maybe precompiled header changes? I'm unsure at this point in the night.

Almost done, though.

**Comment by andrewmcwatters** [comment]
```git-commit
Approved. Intent to merge prior to 12/25/2024.

See https://github.com/Planimeter/hl2sb-2013/pull/8 for more
information.

Remote-tracking branch 'source-sdk-2013-VS2022' at
https://github.com/Planimeter/source-sdk-2013-VS2022.

Signed-off-by: Andrew McWatters <andrew@planimeter.org>
Helped-by: luttje
```

Merry Christmas! https://github.com/Planimeter/hl2sb-2013/pull/8

Thank you, @luttje, @ItzVladik, @ThePixelMoon, @Jacobdeanr!

**Pull request closed without merging**
